### ISSUE TITLE
Suspicious definition of DBState.index_address_statuses

### ISSUE THREAD

**Issue by moodyjon** [lbryio/hub#68]
https://github.com/lbryio/hub/blob/4845b9224842e6800808aa1860330b34929b06ae/hub/db/prefixes.py#L436

```
    def index_address_statuses(self) -> bool:
        return self.bit_fields & 2 == 1
```

...it's always false.

**Comment by jackrobison** [comment]
it's set here: 

https://github.com/lbryio/hub/blob/master/hub/db/prefixes.py#L1477
